import serial


def getOBDData(ser, type, pid):
    cmd = f'{type} {pid}\r'
    ser.write(bytes(cmd))
    resultHEX = str(ser.readline())
    result = float(int('0x'+resultHEX[3]))
    return result


TYPE = {'CURRENT': '01',
        'FREEZE': '02',
        'STORED': '03',
        'CLEAR': '04',
        'TESTR_O2': '05',
        'TESTR_OTHER': '06',
        'DIAG_PEND': '07',
        'CONTROL': '08',
        'REQUEST_VINF': '09',
        'PERMA_DIAG': '0A'}

PID = {
    'DTC_FREEZE': '02',
    'FUEL_SYS_STAT': '03',
    'CALC_ENG_LOAD': '04',
    'COOLANT_TEMP': '05',
    'SHORT_FUEL_B1': '06',
    'LONG_FUEL_B1': '07',
    'SHORT_FUEL_B2': '08',
    'LONG_FUEL_B2': '09',
    'FUEL_PRESSURE': '0A',
    'INT_MAN_ABS_PRES': '0B',
    'REVS': '0C',
    'SPEED': '0D',
    'TIME_ADV': '0E',
    'IN_AIR_TEMP': '0F',
    'MAF_RATE': '10',
    'THROTTLE_POS': '11',
    'SEC_AIR_STAT': '12',
    'O2_SENS_PRES': '13',
    'O2_SENS_1': '14',
    'O2_SENS_2': '15',
    'O2_SENS_3': '16',
    'O2_SENS_4': '17',
    'O2_SENS_5': '18',
    'O2_SENS_6': '19',
    'O2_SENS_7': '1A',
    'O2_SENS_8': '1B',
    'ODB_STANDARDS': '1C',
    'O2_SENSORS_PRESENT': '1D',
    'AUX_IN_STAT': '1E',
    'RUNTIME': '1F',
    'DIST_W_MIL': '21',
    'FR_PRES': '22',
    'FRG_PRES': '23',
    'AF_O2_SENS_1': '24',
    'AF_O2_SENS_2': '25',
    'AF_O2_SENS_3': '26',
    'AF_O2_SENS_4': '27',
    'AF_O2_SENS_5': '28',
    'AF_O2_SENS_6': '29',
    'AF_O2_SENS_7': '2A',
    'AF_O2_SENS_8': '2B',
    'COMM_EGR': '2C',
    'EGR_ERR': '2D',
    'EVOP_PURGE': '2E',
    'FUEL_LEVEL': '2F',
    'WARMUPS_SINCE_CLEARED': '30',
    'DIST_SINCE_CLEAR': '31',
    'EVAP_SYS_PRESS': '32',
    'BARO_PRESS': '33',
    'AF_O2_SENS_11': '34',
    'AF_O2_SENS_12': '35',
    'AF_O2_SENS_13': '36',
    'AF_O2_SENS_14': '37',
    'AF_O2_SENS_15': '38',
    'AF_O2_SENS_16': '39',
    'AF_O2_SENS_17': '3A',
    'AF_O2_SENS_18': '3B',
    'CAT_B1_S1_TEMP': '3C',
    'CAT_B1_S2_TEMP': '3D',
    'CAT_B2_S1_TEMP': '3E',
    'CAT_B2_S2_TEMP': '3F',
    'CONTROL_MOD_V': '42',
    'ABS_LOAD_V': '43',
    'AIR_FUEL_EQV_RAT': '44',
    'RELATIVE_THROTTLE_POS': '45',
    'AIR_TEMP': '46',
    'ABS_THROTTLE_POS_B': '47',
    'ABS_THROTTLE_POS_C': '48',
    'ABS_ACC_POS_D': '49',
    'ABS_ACC_POS_E': '4A',
    'ABS_ACC_POS_F': '4B',
    'COMM_THROT_COMM': '4C',
    'RUN_W_MIL': '4D',
    'TIME_SINCE_CLEAR': '4E',
    'MAX_V_FAR': '4F',
    'MAX_AIR_FLOW': '50',
    'FUEL_TYPE': '51',
    'ETHANOL_PERC': '52',
    'ABS_EVAP_SYS_VAP_PRESS': '53',
    'EVAP_SYS_PRESS': '54',
    'SHORT_O2_TRIM_1': '55',
    'LONG_O2_TRIM_1': '56',
    'SHORT_O2_TRIM_2': '57',
    'LONG_O2_TRIM_2': '58',
    'FUEL_RAIL_ABS_PRESS': '59',
    'REL_ACC_PEDAL_POS': '5A',
    'HYBRID_BATT_PACK_LIFE': '5B',
    'ENGINE_OIL_TEMP': '5C',
    'FUEL_INJ_TIMING': '5D',
    'FUEL_RATE': '5E',
    'EMM_REQ': '5F',
    'DRIVER_DEM_PTQ': '61',
    'ACTUAL_ENG_PTQ': '62',
    'ENG_REFTQ': '63',
    'ENG_PERC_TQD': '64',
    'AUX-INP': '65',
    'MASS_AIRFLOW_SENSOR': '66',
    'ENG_COOLANT_TEMP': '67',
    'INTAKE_AIR_TEMP': '68',
    'ACTUAL_EGR': '69',
    'COMMANDED_DIESEL_IAF_AND_RELATIVE_IAF_POS': '6A',
    'EXHAUST_GAS_RECIRC_TEMP': '6B',
    'COMMANDED_THR_ACT_CONTROL': '6C',
    'FUEL_PRESS_CNTRL_SYS': '6D',
    'INJ_PRESS_CNTRL_SYS': '6E',
    'TURBOCHARGER_COMP_INLET_PRESS': '6F',
    'BOOST_PRESS_CNTRL': '70',
    'VGT_CNTRL': '71',
    'WASTEGATE_CNTRL': '72',
    'EXHAUST_PRESSURE': '73',
    'TURBOCHARGER_RPM': '74',
    'TURBOCHARGER_TEMP': '75',
    'TURBOCHARGER_TEMP': '76',
    'CAC_TEMP': '77',
    'EGT_BANK_1': '78',
    'EGT_BANK_2': '79',
    'DPF_DIFF_PRESS': '7A',
    'DPF': '7B',
    'DPF_TEMP': '7C',
    'NOX_NTE_CNTRL_A_STAT': '7D',
    'PM_NTE_CNTRL_A_STAT': '7E',
    'ENG_RUNTIME': '7F',
    'AECD': '81',
    'AECD': '82',
    'NOX_SENS': '83',
    'MANIF_SURF_TEMP': '84',
    'NOX_REAG_SYS': '85',
    'PM_SENSOR': '86',
    'INT_MANIF_ABS_PRESS': '87',
    'SCR_INDUCE_SYSTEM': '88',
    'RUNTIME_AECD_11-15': '89',
    'RUNTIME_AECD_16-20': '8A',
    'DIESEL_AFTERTREATMENT': '8B',
    'O2_SENS_WIDE': '8C',
    'THROTTLE_POS_G': '8D',
    'ENG_FRICT_PERCTQ': '8E',
    'PM_SENSOR_BANK_1-2': '8F',
    'WWH-OBD_VOBDSI': '90',
    'WWH-OBD_VOBDSI': '91',
    'FUEL_SYS_CONTROL': '92',
    'WWH-OBD_VOBDCSUPPORT': '93',
    'NOX_WARN_AND_INDUCE_SYSTEM': '94',
    'EXHAUST_GAS_TEMP_SENSOR': '98',
    'EXHAUST_GAS_TEMP_SENSOR': '99',
    'HYBRID/EV_SYS_DATA-B-V': '9A',
    'DIESEL_EXHAUST_FLUID_SENS_DATA': '9B',
    'O2_SENS_DATA': '9C',
    'ENG_FUEL_RATE': '9D',
    'ENG_EXHAUST_FLOW_RATE': '9E',
    'FUEL_SYS_PERC_DATA': '9F',
    'NOX_SENS_CORRECTED_DATA': 'A1',
    'CYLINDER_FUEL_RATE': 'A2',
    'EVAP_SYSTEM_VAP_PRESSURE': 'A3',
    'TRANS_ACTUAL_GEAR': 'A4',
    'COMMANDED_DIESEL_EXHAUST_FLUID_DOSING': 'A5',
    'ODOMETER': 'A6',
    'NOX_SENS_CONCENTRATION_SENS_3-4': 'A7',
    'NOX_SENS_CORRECTED_SENS_3-4': 'A8',
    'ABS_DISABLE_SWITCH_STATE': 'A9',
}

ser = serial.Serial('COM5', 38400, timeout=1)
ser.write(b"01 0D \r")
speed_hex = str(ser.readline())
speed = float(int('0x'+speed_hex[3], 0))
print("Speed: ", speed, "km/h")
ser.write(b"01 0C \r")
rpm_hex = str(ser.readline())
rpm = float(int('0x'+rpm_hex[3], 0))
print(speed, "RPM")
ser.write(b"01 11 \r")
tpos_hex = str(ser.readline())
tpos = float(int('0x'+tpos_hex[3], 0))
print(speed, "RPM")
ser.write(b"01 51 \r")
ftype_hex = str(ser.readline())
ftype = float(int('0x'+ftype_hex[3], 0))
print(ftype)
